declare const isPalindrome: () => void;
declare const isLinkedListPalindrome: () => void;
declare const getFibonacciNumber: () => void;
declare const isAnagram: () => void;
declare const getSumOfNumbers: () => void;
declare const getMaxProfit: () => void;
declare const secondLargestSome: () => void;
declare const rotateArray: () => void;
declare const isCyclicLinkedList: () => void;
declare const concatSortedLinkedList: () => void;
export { isPalindrome, getFibonacciNumber, isAnagram, getSumOfNumbers, getMaxProfit, secondLargestSome, rotateArray, isLinkedListPalindrome, isCyclicLinkedList, concatSortedLinkedList };
