import * as promiseTypes from './Topics/promises';
import Calculator from './Topics/calculator';
import calculateTicketTime from './Topics/ticket-time-calculate';
import { lengthOfLastWord } from './Topics/string';
import ChangeColor from './Projects/asyncProjects/change_background_color/change-background-color';
import { addCircle } from './Projects/circle-generator';
import { nonWritableObject } from './Topics/objects';
import { testEvent } from './Topics/events';
import { executeMemoiseFunction, executeGeneratorMemoiseFn } from './Topics/memoization';
import closure from './Topics/closures';
import { testGeneratorFunction } from './Topics/generator';
export declare const provider: {
    promise: typeof promiseTypes;
    Calculator: typeof Calculator;
    calculateTicketTime: typeof calculateTicketTime;
    lengthOfLastWord: typeof lengthOfLastWord;
    ChangeColor: typeof ChangeColor;
    addCircle: typeof addCircle;
    nonWritableObject: typeof nonWritableObject;
    testEvent: typeof testEvent;
    executeMemoiseFunction: typeof executeMemoiseFunction;
    closure: typeof closure;
    testGeneratorFunction: typeof testGeneratorFunction;
    executeGeneratorMemoiseFn: typeof executeGeneratorMemoiseFn;
};
